#!/bin/bash
# Created by the VLSCI job script generator for SLURM on x86
# Fri Jul 04 2014 15:32:59 GMT+1000 (EST)

# check that the script is launched with sbatch
if [ "x$SLURM_JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with sbatch"
   exit 1
fi

# Partition for the job:
#SBATCH -p main

# The name of the job:
#SBATCH --job-name=raft_se

# Maximum number of CPU cores used by the job:
#SBATCH --ntasks=8

# The amount of memory in megabytes per process in the job:
#SBATCH --mem-per-cpu=64000

# Send yourself an email when the job:
# ends successfully
#SBATCH --mail-type=END

# Send yourself an email when the job:
# starts successfully
#SBATCH --mail-type=BEGIN

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-32:0:00

# Run the job from the directory where it was launched (default):

# The modules to load:
module load bedtools-intel/2.17.0
module load python-gcc/2.7.5
module load bwa-intel/0.7.5a
module load samtools-intel/1.3.1

source $HOME/scratch/raft_hotspots_se_dev/bin/activate

./pipeline.sh -v -r U13369.1_hg19.fa -f SRR944107.fastq -p SRRbla_hg19 -b hg19.blacklist.sort.bed -s hg19_GATC5.bed 
